config:
  selfUrl: # https://bookstore-st-gateway-public-web
  globalConfigurationBaseUrl: # http://bookstore-st-gateway-public-web
  corsOrigins: # https://bookstore-st-gateway-web,https://bookstore-st-gateway-public-web
  authServer:
    authority: # http://bookstore-st-authserver
    requireHttpsMetadata: # "false"
    swaggerClientId: # WebGateway_Swagger
  dotnetEnv: Staging 
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #

reRoutes:
  accountService:
    schema: http
    host: bookstore-st-authserver
    port: 80
  saasService:
    schema: http
    host: bookstore-st-saas
    port: 80
  administrationService:
    schema: http
    host: bookstore-st-administration
    port: 80
  productService:
    schema: http
    host: bookstore-st-product
    port: 80  

ingress:
  host: bookstore-st-gateway-web-public
  tlsSecret: bookstore-tls

image:
  repository: acme/bookstore-gateway-web-public
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    